blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', blogIndex, name='blogIndex'),
    path('blog/<int:postId>', singleView, name='singleView'),
    path('blog/category/<str:catName>', blogIndex, name='category'),
    path('blog/author/<int:authorId>', blogIndex, name='author'),
    path('contact', contactView, name='blogContact'),
    path('index', index, name='index'),

]

practiceDataBase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class User(models.Model):
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=100)
    birthday = models.DateField()
    email = models.EmailField()
    image = models.ImageField(upload_to='users/%Y/%m/%d/', default='users/default.jpg')
    description = models.TextField()
    createAt = models.DateTimeField(auto_now_add=True)
    updateAt = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.firstName} {self.lastName}"


class Tags(models.Model):
    name = models.CharField(max_length=30)
    createAt = models.DateTimeField(auto_now_add=True)
    updateAt = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    subject = models.CharField(max_length=20)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = models.ManyToManyField(Tags)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='blog/%Y/%m/%d/', default='blog/default.jpg')
    pubDate = models.DateTimeField()
    createAt = models.DateTimeField(auto_now_add=True)
    updateAt = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False)
    viewCount = models.IntegerField(default=0)

    class Meta:
        ordering = ('-pubDate',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=25)
    email = models.EmailField()
    userWebSite = models.URLField()
    comment = models.TextField()
    createAt = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class ContactUs(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phoneNumber = models.IntegerField()
    subject = models.CharField(max_length=255, null=True, blank=True)
    message = models.TextField()
    createAt = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

blog/forms.py
from django.forms import ModelForm
from blog.models import ContactUs


class ContactForm(ModelForm):
    class Meta:
        model = ContactUs
        fields = '__all__'

blog/views.py
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from blog.models import *
from blog.forms import ContactForm


def index(request):
    return render(request, 'index.html')


def blogIndex(requests, **kwargs):
    posts = Post.objects.filter(pubDate__lte=timezone.now(), status=True)

    if kwargs.get('catName') is not None:
        posts = Post.objects.filter(pubDate__lte=timezone.now(), status=True, tags__name=kwargs.get('catName'))
    if kwargs.get('authorId') is not None:
        posts = Post.objects.filter(pubDate__lte=timezone.now(), status=True, author=kwargs.get('authorId'))

    posts = Paginator(posts, 3)

    try:
        pageNumber = requests.GET.get('page')
        posts = posts.get_page(pageNumber)
    except PageNotAnInteger:
        posts = posts.get_page(2)
    except EmptyPage:
        posts = posts.get_page(2)

    content = {
        'posts': posts,
    }
    return render(requests, 'blog/marketing-blog.html', content)


def singleView(requests, postId):
    global prevIndex
    posts = Post.objects.all().filter(status=True, pubDate__lte=timezone.now())
    post = get_object_or_404(posts, pk=postId)

    author = User.objects.get(id=post.author.id)
    comments = Comment.objects.filter(post=post)

    post.viewCount += 1
    post.save()

    prevPost = None
    nextPost = None
    for i, element in enumerate(posts):
        if element == post:
            prevIndex = i - 1
            nextIndex = i + 1

            if prevIndex >= 0:
                prevPost = posts[prevIndex]
            else:
                prevPost = None

            if nextIndex <= len(posts) - 1:
                nextPost = posts[nextIndex]
            else:
                nextPost = None

    content = {
        'post': post,
        'author': author,
        'comments': comments,
        'prevPost': prevPost,
        'nextPost': nextPost
    }

    return render(requests, 'blog/marketing-single.html', content)


def contactView(requests):

    if requests.method == 'POST':
        form = ContactForm(requests.POST)

        if form.is_valid():
            form = form.cleaned_data
            form['name'] = 'Anonymous'

            ContactUs.objects.create(name=form['name'],
                                     email=form['email'],
                                     phoneNumber=form['phoneNumber'],
                                     subject=form['subject'],
                                     message=form['message'])

            messages.success(requests, "Information was sent successfully!")
            return HttpResponseRedirect('/contact')

    form = ContactForm()
    return render(requests, 'blog/marketing-contact.html', {'form': form})

templates/base.html
{% load static %}
{% load blogTags %}

<!DOCTYPE html>
<html lang="en">

<!-- Basic -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<!-- Mobile Metas -->
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Site Metas -->
<title>Markedia - Marketing Blog Template</title>
<meta name="keywords" content="">
<meta name="description" content="">
<meta name="author" content="">

<!-- Site Icons -->
<link rel="shortcut icon" href={% static "images/favicon.ico" %}type="image/x-icon"/>
<link rel="apple-touch-icon" href={% static "images/apple-touch-icon.png" %}>

<!-- Design fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,700" rel="stylesheet">

<!-- Bootstrap core CSS -->
<link href={% static "css/bootstrap.css" %} rel="stylesheet">

<!-- FontAwesome Icons core CSS -->
<link href={% static "css/font-awesome.min.css" %} rel="stylesheet">

<!-- Custom styles for this template -->
<link href={% static "css/style.css" %} rel="stylesheet">

<!-- Animate styles for this template -->
<link href={% static "css/animate.css" %} rel="stylesheet">

<!-- Responsive styles for this template -->
<link href={% static "css/responsive.css" %} rel="stylesheet">

<!-- Colors for this template -->
<link href={% static "css/colors.css" %} rel="stylesheet">

<!-- Version Marketing CSS for this template -->
<link href={% static "css/version/marketing.css" %} rel="stylesheet">

<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

</head>
<body>

<div id="wrapper">
    <header class="market-header header">
        <div class="container-fluid">
            <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                        data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="{% url 'blog:blogIndex' %}"><img
                        src={% static "images/version/market-logo.png" %} alt=""></a>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:blogIndex' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:blogContact' %}">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:index' %}">Index</a>
                        </li>
                    </ul>
                    <form class="form-inline">
                        <input class="form-control mr-sm-2" type="text" placeholder="How may I help?">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </nav>
        </div><!-- end container-fluid -->
    </header><!-- end market-header -->


{% include 'blog/messages.html' %}


    {% block content %}

    {% endblock %}



    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">

                    {% recentPost %}

                </div><!-- end col -->

                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                    <div class="widget">
                        <a href="{% url 'blog:blogContact' %}">

                            <h2 class="widget-title">About Us</h2>
                        </a>

                        <div class="blog-list-widget">
                            <div class="list-group">

                                <div class="w-100 last-item justify-content-between">
                                    <h5 class="mb-1">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                        Atque, commodi, corporis id libero nostrum officia pariatur, quaerat sed
                                        temporibus veniam voluptas voluptates. Ducimus enim est incidunt nesciunt
                                        tempore vero voluptatem voluptates. Adipisci distinctio dolorum ducimus
                                        eaque maiores non, nostrum voluptatum. Ipsa libero, repellat. Aliquam
                                        architecto, dolore in minus quis repellendus.</h5>
                                </div>
                            </div>
                        </div><!-- end blog-list -->
                    </div><!-- end widget -->
                </div><!-- end col -->

                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">

                    {% popCat %}

                </div><!-- end col -->
            </div><!-- end row -->
            <div class="row">
                <div class="col-md-12 text-center">
                    <br>
                    <br>
                    <div class="copyright">&copy; Markedia. Design: <a href="http://html.design">HTML Design</a>.</div>
                </div>
            </div>
        </div><!-- end container -->
    </footer><!-- end footer -->


</div><!-- end wrapper -->

<!-- Core JavaScript
================================================== -->
<script src={% static "js/jquery.min.js" %}></script>
<script src={% static "js/tether.min.js" %}></script>
<script src={% static "js/bootstrap.min.js" %}></script>
<script src={% static "js/animate.js" %}></script>
<script src={% static "js/custom.js" %}></script>

</body>
</html>

templates/blog/blog-popularCategories.html
{% load static %}

<div class="widget">
    <h2 class="widget-title">Popular Categories</h2>
    <div class="link-widget">

        {% for cat in category %}
            <ul>
                <li><a href="#">{{ cat.name }} <span>({{ cat.repetitions }})</span></a></li>
            </ul>
        {% endfor %}
    </div><!-- end link-widget -->
</div><!-- end widget -->

templates/blog/blog-recentPost.html
{% load static %}

<div class="widget">
    <h2 class="widget-title">Recent Posts</h2>
    <div class="blog-list-widget">
        <div class="list-group">
            {% for recent in recentPost %}
                <a href="{% url 'blog:singleView' postId=recent.id %}"
                   class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="w-100 justify-content-between">
                        <img src="media/{{ recent.image }}" alt="" class="img-fluid float-left">
                        <h5 class="mb-1">{{ recent.title }}</h5>

                        <small>{{ recent.pubDate | date:"D d M Y" }}</small>
                    </div>
                </a>
            {% endfor %}

        </div>
    </div><!-- end blog-list -->
</div><!-- end widget -->

templates/blog/include/blog-popularCategories.html
{% load static %}

<div class="widget">
    <h2 class="widget-title">Popular Categories</h2>
    <div class="link-widget">

        {% for name, count in categoties.items %}
            <ul>
                <li><a href="{% url 'blog:category' catName=name %}">{{ name }} <span>({{ count }})</span></a></li>
            </ul>
        {% endfor %}
    </div><!-- end link-widget -->
</div><!-- end widget -->

templates/blog/include/blog-recentPost.html
{% load static %}

<div class="widget">
    <h2 class="widget-title">Recent Posts</h2>
    <div class="blog-list-widget">
        <div class="list-group">
            {% for recent in posts %}
                <a href="{% url 'blog:singleView' postId=recent.id %}"
                   class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="w-100 justify-content-between">
                        <img src="media/{{ recent.image }}" alt="" class="img-fluid float-left">
                        <h5 class="mb-1">{{ recent.title }}</h5>

                        <small>{{ recent.pubDate | date:"D d M Y" }}</small>
                    </div>
                </a>
            {% endfor %}

        </div>
    </div><!-- end blog-list -->
</div><!-- end widget -->

templates/blog/marketing-blog.html
{% extends 'base.html' %}
{% load static %}
{% load blogTags %}


{% block content %}
    <div class="page-title db">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <h2> Blog <small class="hidden-xs-down hidden-sm-down">for All </small></h2>
                </div><!-- end col -->

            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end page-title -->

    <section class="section lb">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                    <div class="page-wrapper">
                        <div class="blog-custom-build">

                            {% for post in posts %}

                                <div class="blog-box wow fadeIn">
                                    <div class="post-media">
                                        <a href="{% url 'blog:singleView' postId=post.id %}">
                                            <img src="{{ post.image.url }}" alt="" class="img-fluid">
                                            <div class="hovereffect">
                                                <span></span>
                                            </div>
                                            <!-- end hover -->
                                        </a>
                                    </div>
                                    <!-- end media -->
                                    <div class="blog-meta big-meta text-center">

                                        <h4><a href="{% url 'blog:singleView' postId=post.id %}">{{ post.title }}</a>
                                        </h4>
                                        <p>{{ post.content|truncatewords:15 }}</p>
                                        <small><a href="#" title="">{{ post.pubDate | date:"D d M YD d M Y" }}</a></small>
                                        <small><a href="#" title="">by {{ post.author }}</a></small>
                                        <small><a href="#" title=""><i class="fa fa-eye"></i> {{ post.viewCount }}
                                        </a></small>

                                    </div><!-- end meta -->

                                </div><!-- end blog-box -->
                                <hr class="invis">


                            {% endfor %}


                        </div>
                    </div>

                    <hr class="invis">

                    <div class="row">
                        <div class="col-md-12">
                            <nav aria-label="Page navigation">
                                <ul class="pagination justify-content-center">

                                    {% if posts.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a>
                                    </li>
                                    {% endif %}

                                    {% for i in posts.paginator.page_range %}
                                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                    {% endfor %}

                                    {% if posts.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a>
                                    </li>
                                    {% endif %}

                                </ul>
                            </nav>
                        </div><!-- end col -->
                    </div><!-- end row -->
                </div><!-- end col -->

                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                    <div class="sidebar">


                        {% subscribe %}

                        {% recentPost %}

                        {% popCat %}


                    </div><!-- end sidebar -->
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </section>

{% endblock %}

templates/blog/marketing-contact.html
{% extends 'base.html' %}
{% load static %}
{% load blogTags %}

{% block content %}

        <div class="page-title db">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                        <h2>Contact <small class="hidden-xs-down hidden-sm-down">Be in touch with us... </small></h2>
                    </div><!-- end col -->

                </div><!-- end row -->
            </div><!-- end container -->
        </div><!-- end page-title -->

        <section class="section lb">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                        <div class="sidebar">

                    {% subscribe %}


                        </div><!-- end sidebar -->
                    </div><!-- end col -->
                    
                    <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                        <div class="page-wrapper">
                            <div class="row">
                                <div class="col-lg-6">
                                    <h4>Who we are</h4>
                                    <p>Markedia is a personal blog for handcrafted, cameramade photography content, fashion styles from independent creatives around the world.</p>
                                </div>

                                <div class="col-lg-6">
                                    <h4>How we help?</h4>
                                    <p>If you’d like to write for us, <a href="#">advertise with us</a> or just say hello, fill out the form below and we’ll get back to you as soon as possible.</p>
                                </div>
                            </div><!-- end row -->

                            <hr class="invis">

                            <div class="row">
                                <div class="col-lg-12">

                                    <form class="form-wrapper" action="{% url 'blog:blogContact' %}" method="post">
                                        {% csrf_token %}

                                        <h4>Contact form</h4>
                                        <input type="text" name="name" class="form-control" placeholder="Your name">
                                        <input type="text" name="email" class="form-control" placeholder="Email address">
                                        <input type="text" name="phoneNumber" class="form-control" placeholder="Phone">
                                        <input type="text" name="subject" class="form-control" placeholder="Subject">
                                        <textarea name="message" class="form-control" placeholder="Your message"></textarea>
                                        <button type="submit" class="btn btn-primary">Send <i class="fa fa-envelope-open-o"></i></button>
                                    </form>

                                </div>
                            </div>
                        </div><!-- end page-wrapper -->
                    </div><!-- end col -->
                </div><!-- end row -->
            </div><!-- end container -->
        </section>

{% endblock %}

templates/blog/marketing-single.html
{% extends 'base.html' %}
{% load static %}
{% load blogTags %}

{% block content %}


    <section class="section lb m3rem">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                    <div class="page-wrapper">
                        <div class="blog-title-area">


                            <span class="color-yellow"><a href="#" title="">{{ post.subject }}</a></span>

                            <h3>{{ post.title }}</h3>

                            <div class="blog-meta big-meta">
                                <small><a href="#" title="">{{ post.pubDate | date:"D d M Y" }}</a></small>
                                <small><a href="#" title="">by {{ author }}</a></small>
                                <small><a href="#" title=""><i class="fa fa-eye"></i> {{ post.viewCount }} </a></small>


                            </div><!-- end meta -->

                        </div><!-- end title -->

                        <div class="single-post-media">
                            <img src="{{ post.image.url }}" alt="" class="img-fluid">
                        </div><!-- end media -->

                        <div class="blog-content">


                            <div class="pp">
                                <p>{{ post.content }}</p>

                            </div><!-- end pp -->
                        </div><!-- end content -->

                        <div class="blog-title-area">
                            <div class="tag-cloud-single">
                                <span>Tags</span>

                                {% for tag in post.tags.all %}

                                <small><a href="{% url 'blog:category' catName=tag.name %}" title="">{{ tag.name }}</a></small>
                                {% endfor %}
                            </div><!-- end meta -->

                            <div class="post-sharing">
                                <ul class="list-inline">


                                    {% if prevPost != Noun %}

                                        <li><a href="{% url 'blog:singleView' postId=prevPost.id %}"
                                               class="fb-button btn btn-primary"><i></i>
                                            <span class="down-mobile">Next Post</span></a></li>
                                    {% else %}
                                        <li><a class="fb-button btn btn-primary"><i></i>
                                            <span class="down-mobile">Next Post</span></a></li>
                                    {% endif %}


                                    {% if nextPost != Noun %}
                                        <li><a href="{% url 'blog:singleView' postId=nextPost.id %}"
                                               class="tw-button btn btn-primary"><i></i>
                                            <span class="down-mobile">Previous Post</span></a></li>
                                    {% else %}
                                        <li><a class="tw-button btn btn-primary"><i></i>
                                            <span class="down-mobile">Previous Post</span></a></li>
                                    {% endif %}

                                </ul>
                            </div><!-- end post-sharing -->
                        </div><!-- end title -->


                        <hr class="invis1">

                        <div class="custombox authorbox clearfix">
                            <h4 class="small-title">About author</h4>
                            <div class="row">
                                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                    <img src="{{ author.image.url }}" alt="" class="img-fluid rounded-circle">
                                </div><!-- end col -->

                                <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
                                    <h4><a href="#">{{ author }}</a></h4>
                                    <p>{{ author.description }}</p>

                                </div><!-- end col -->
                            </div><!-- end row -->
                        </div><!-- end author-box -->

                        <hr class="invis1">


                        <hr class="invis1">


                        <div class="custombox clearfix">
                            <h4 class="small-title">{{ comments.count }} Comments</h4>
                            <div class="row">
                                {% for comment in comments %}

                                    <div class="col-lg-12">
                                        <div class="comments-list">
                                            <div class="media">
                                                <div class="media-body">
                                                    <h4 class="media-heading user_name">{{ comment.name }} <small>
                                                        {{ comment.createAt }}
                                                    </small></h4>
                                                    <p>{{ comment.comment }}</p>
                                                </div>
                                            </div>

                                        </div>
                                    </div><!-- end col -->
                                {% endfor %}

                            </div><!-- end row -->
                        </div><!-- end custom-box -->


                        <hr class="invis1">

                        <div class="custombox clearfix">
                            <h4 class="small-title">Add Comment</h4>
                            <div class="row">
                                <div class="col-lg-12">
                                    <form class="form-wrapper">
                                        <input type="text" class="form-control" placeholder="Your name">
                                        <input type="text" class="form-control" placeholder="Email address">
                                        <input type="text" class="form-control" placeholder="Website">
                                        <textarea class="form-control" placeholder="Your comment"></textarea>
                                        <button type="submit" class="btn btn-primary">Submit Comment</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div><!-- end page-wrapper -->
                </div><!-- end col -->

                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                    <div class="sidebar">

                    {% subscribe %}

                    {% recentPost %}

                    {% popCat %}

                    </div><!-- end sidebar -->
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </section>

{% endblock %}

templates/includeIndex.html
{% load static %}

<section class="recent-blog-area section-gap">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="menu-content pb-60 col-lg-9">
                <div class="title text-center">
                    <h1 class="mb-10">Latest from Our Blog</h1>
                    <p>With the exception of Nietzsche, no other madman has contributed so much to human sanity as
                        has.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="active-recent-blog-carusel">


                {% for post in posts %}
                <div class="single-recent-blog-post item">
                    <div class="thumb">
                        <img style="max-height: 200px" class="img-fluid" src="media/{{ post.image }}" alt="" height="10px">
                    </div>
                    <div class="details">
                        <div class="tags">
                            <ul>
                                {% for tag in post.tags.all %}
                                <li>
                                    <a href="{% url 'blog:category' catName=tag.name %}">{{ tag.name }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <a href="{% url 'blog:singleView' postId=post.id %}"><h4 class="title">{{ post.title }}</h4></a>
                        <p>
                            {{ post.content|truncatewords:15 }}
                        </p>
                        <h6 class="date">{{ post.pubDate|date:'D d M Y' }}</h6>
                    </div>
                </div>

                {% endfor %}


            </div>
        </div>
    </div>
</section>